### ISSUE TITLE
larawiz.com website is down

### ISSUE THREAD

**Issue by szepeviktor** [Larawiz/issues#1]
### Explanation

```
$ curl -vvv https://larawiz.com/
*   Trying 192.64.119.249...
* TCP_NODELAY set
```

### Blueprint

```yaml
models:
```

### Error

```php
no connection
```

### Are you a Sponsor?

Yes, get this resolved quickly

**Comment by DarkGhostHunter** [comment]
I'll fix next 48 hours while I find a hosting and make the CICD.

**Comment by szepeviktor** [comment]
@DarkGhostHunter Choose [Viktor hosting](https://github.com/szepeviktor/debian-server-tools/blob/master/Onboarding.md) please.
It is word-class and free for the first year (I do not have anything to do).

**Comment by DarkGhostHunter** [comment]
> @DarkGhostHunter Choose [Viktor hosting](https://github.com/szepeviktor/debian-server-tools/blob/master/Onboarding.md) please. It is word-class and free for the first year (I do not have anything to do).

I just barely understood. Links to good hostings are welcome.

**Comment by szepeviktor** [comment]
Let me run your website/web application. But you own/administer your accounts at service providers (see Specialized providers in Onboarding)
Please do not choose an all-in-one-no-one-cares-about-it solution. Viktor is free for 1 year!

**Comment by DarkGhostHunter** [comment]
I will check my options later. [Docs are up](https://larawiz.github.io/docs/) but the search is awol.
