### ISSUE TITLE
Generating API Controllers

### ISSUE THREAD

**Issue by skills-up** [Larawiz/issues#5]
Hello,

I've recently discovered Larawiz, and giving it a try. I've created a test project, and it appears to work fine.

I've a couple of queries regarding the generated controllers and requests though:

1. How can be generated API controllers instead of view based controllers (return JSON instead of views)
2. How can we auto generate validation rules based on migration schema, in the requests

I hope these queries are relevant and can be answered quickly.

**Comment by DarkGhostHunter** [comment]
> 1. How can be generated API controllers instead of view based controllers (return JSON instead of views)

That would need a global flag. View Controllers are hard-coded.

> 2. How can we auto generate validation rules based on migration schema, in the requests.

Compared to the prior version, I considered that _guessing_ the attributes of models to be faked was too much convoluted and prone to _dumb guessing_ that I left it out on purpose.

Before adding validation rules, I need to figure out attribute guessing. After that, may come validation rules guessing. That will work hands-in-hands on what Faker offers. 

---

I would like to give time to these but I'm hands full and there is 0 sponsors, which signals me this project is not worth full time investment. I may add them later, but not right now.
